sonar.projectKey=MiFutbolC
sonar.projectName=MiFutbolC
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=c
sonar.sourceEncoding=UTF-8
sonar.cfamily.build-wrapper-output=bw-output
sonar.cfamily.gcov.reportsPath=.
sonar.cfamily.threads=4
sonar.exclusions=build-wrapper-dump.json,bw-output/**,*.pb.c,*.pb.h,doxygen/**,docs/**,tests/**,html/**,*.md,*.txt,*.json,*.yml,*.xml,*.png,*.jpg,*.jpeg,*.gif,*.svg,*.ico,doxygen.config,*.logs,doxygen/html/**,external/**,third_party/**,vendor/**,cjson/**,cmake-build-*/*/**,sqlite3/**,lib/**,examples/**,*.sh,*.bat,sqlite3.c,sqlite3.h,cJSON_Utils.c,cJSON_Utils.h,cJSON.c,cJSON.h
