sonar.projectKey=thomashamer3_MiFutbolC-GUI
sonar.organization=thomashamer3

sonar.projectName=MiFutbolC-GUI
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.host.url=https://sonarcloud.io
sonar.token=TU_TOKEN

sonar.cfamily.build-wrapper-output=bw-output
sonar.cfamily.threads=4

sonar.exclusions=**/bw-output/**,**/build-wrapper-dump.json,**/*.md,**/*.json,**/*.yml,**/docs/**,**/tests/**